%% function s=printDjoint(mdp,t)
function s=printDjoint(mdp,t)
Nagents=length(mdp);
Tn=nan(Nagents,1);
TnV=nan(Nagents,1);

for n=1:Nagents
    Tn(n)=length(mdp{n});
    TnV(n)=size(mdp{n}{end}.V,1);
end
Tmax=min(Tn);
TVmax=min(TnV);
s='';
%fprintf('\nMirror game with two agents. Leader: agent %d; Target: %s.\n\n',par.wholeads,par.target);
if t==1
    s=sprintf('Time: %g; N. Agents %g;\t\tLocations: (%g,%g)',        ...
            t-1,                                                  ...
            Nagents,                                            ...
            find(mdp{1}{t}.S{1}(:,t)),find(mdp{2}{t}.S{1}(:,t)) ...
            );
elseif t<Tmax
    s=sprintf('Time: %g; Actions: (%s,%s);\tLocations: (%g,%g);\tBeliefs[(%.2f,%.2f,%.2f,%.2f) , (%.2f,%.2f,%.2f,%.2f)].',    ...
            t-1,                                                                                                              ...
            actionString(mdp{1}{t}.u(t-1)),actionString(mdp{2}{t}.u(t-1)),                                                  ...
            mdp{1}{t}.s(1,t),mdp{2}{t}.s(1,t),                                                                            ...
            mdp{1}{t}.X{2}(:,t-1),mdp{2}{t}.X{2}(:,t-1)                                                                     ...
            );
elseif t==Tmax && t<TVmax
    s=sprintf('Time: %g; Actions: (%s,%s);\tLocations: (%g,%g);\tBeliefs[(%.2f,%.2f,%.2f,%.2f) , (%.2f,%.2f,%.2f,%.2f)].',    ...
            t-1,                                                                                                              ...
            actionString(mdp{1}{t}.u(t-1)),actionString(mdp{2}{t}.u(t-1)),                                                  ...
            mdp{1}{t}.s(1,t),mdp{2}{t}.s(1,t),                                                                              ...   
            mdp{1}{t}.X{2}(:,t-1),mdp{2}{t}.X{2}(:,t-1)                                                                     ...
            );
elseif t==TVmax
    s=sprintf('Time: %g; Actions: (%s,%s);\tBeliefs[(%.2f,%.2f,%.2f,%.2f) , (%.2f,%.2f,%.2f,%.2f)].',    ...
            t-1,                                                                                                              ...
            actionString(mdp{1}{t}.u(t-1)),actionString(mdp{2}{t}.u(t-1)),                                                  ...
            mdp{1}{t}.X{2}(:,t-1),mdp{2}{t}.X{2}(:,t-1)                                                                     ...
            );
end
if s
    fprintf('%s\n',s);
end